### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sofer**

### CODE REVIEW

**Comment by sofer** [comment]
A complaints procedure!

Are you OK with this?

(we have been asked for it by the Skills Funding Agency)

**Comment by nelsonic** [comment]
reads well. 
@iteles is *temporarily* offline ... 
is it ok to get this merged tomorrow morning?
does anyone else have input/insight?

**Comment by iteles** [comment]
Looks good @sofer, thanks!

Is this email address currently routing to you or both of us or more people (such as @rub1e)?

**Comment by rub1e** [comment]
Sorry, just saw this. Looks fine - assume this is a borrowed pro forma? 

Don't mind adding complaints@ to my list if you want - can't imagine it will be a full-time job... let me know

**Pull request merged**
